name: user_repository
description: User Repository package
publish_to: none

environment:
  sdk: ">=3.1.0-22.0.dev <4.0.0"

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.0

dev_dependencies:
  very_good_analysis: ^3.1.0
